package emoji

// Entry is one emoji in the built-in picker set.
type Entry struct {
	Cluster string
	Name    string
	// Keywords back the picker's search box.
	Keywords []string
}

// Catalog returns the built-in Unicode emoji set backing the ctrl+e picker. It
// is compiled in and needs no credentials and no network.
//
// The set is curated rather than exhaustive: a live-chat composer wants the
// couple of hundred emoji people actually send during a stream, reachable in a
// few keystrokes, not the full Unicode table. Every entry is a valid cluster
// under IsCluster, so what the picker inserts is what the renderer measures.
// Channel emoji are deliberately absent - the API returns them only as
// ":_shortcode:" literals with no glyph to show.
func Catalog() []Entry {
	return append([]Entry(nil), catalog...)
}

var catalog = []Entry{
	// Reactions. The top of the list is what a chat sends most.
	{Cluster: "😀", Name: "grinning face", Keywords: []string{"smile", "happy", "grin"}},
	{Cluster: "😃", Name: "grinning face with big eyes", Keywords: []string{"smile", "happy"}},
	{Cluster: "😄", Name: "grinning face with smiling eyes", Keywords: []string{"smile", "happy"}},
	{Cluster: "😁", Name: "beaming face", Keywords: []string{"grin", "smile"}},
	{Cluster: "😆", Name: "grinning squinting face", Keywords: []string{"laugh", "haha"}},
	{Cluster: "😅", Name: "grinning face with sweat", Keywords: []string{"laugh", "relief", "phew"}},
	{Cluster: "🤣", Name: "rolling on the floor laughing", Keywords: []string{"rofl", "laugh", "lol"}},
	{Cluster: "😂", Name: "face with tears of joy", Keywords: []string{"lol", "laugh", "cry"}},
	{Cluster: "🙂", Name: "slightly smiling face", Keywords: []string{"smile"}},
	{Cluster: "🙃", Name: "upside-down face", Keywords: []string{"silly", "irony"}},
	{Cluster: "😉", Name: "winking face", Keywords: []string{"wink"}},
	{Cluster: "😊", Name: "smiling face with smiling eyes", Keywords: []string{"blush", "happy"}},
	{Cluster: "😇", Name: "smiling face with halo", Keywords: []string{"angel", "innocent"}},
	{Cluster: "🥰", Name: "smiling face with hearts", Keywords: []string{"love", "adore"}},
	{Cluster: "😍", Name: "smiling face with heart-eyes", Keywords: []string{"love", "crush"}},
	{Cluster: "😘", Name: "face blowing a kiss", Keywords: []string{"kiss", "love"}},
	{Cluster: "😋", Name: "face savoring food", Keywords: []string{"yum", "tasty"}},
	{Cluster: "😜", Name: "winking face with tongue", Keywords: []string{"silly", "joke"}},
	{Cluster: "🤪", Name: "zany face", Keywords: []string{"goofy", "wild"}},
	{Cluster: "🤨", Name: "face with raised eyebrow", Keywords: []string{"suspicious", "doubt"}},
	{Cluster: "🧐", Name: "face with monocle", Keywords: []string{"inspect", "hmm"}},
	{Cluster: "🤓", Name: "nerd face", Keywords: []string{"glasses", "geek"}},
	{Cluster: "😎", Name: "smiling face with sunglasses", Keywords: []string{"cool", "sunglasses"}},
	{Cluster: "🥳", Name: "partying face", Keywords: []string{"party", "celebrate"}},
	{Cluster: "😏", Name: "smirking face", Keywords: []string{"smirk", "smug"}},
	{Cluster: "😒", Name: "unamused face", Keywords: []string{"meh", "unimpressed"}},
	{Cluster: "😔", Name: "pensive face", Keywords: []string{"sad", "thoughtful"}},
	{Cluster: "😴", Name: "sleeping face", Keywords: []string{"sleep", "zzz", "bored"}},
	{Cluster: "😪", Name: "sleepy face", Keywords: []string{"tired", "sleep"}},
	{Cluster: "🤤", Name: "drooling face", Keywords: []string{"drool", "hungry"}},
	{Cluster: "😷", Name: "face with medical mask", Keywords: []string{"sick", "mask"}},
	{Cluster: "🤒", Name: "face with thermometer", Keywords: []string{"sick", "fever"}},
	{Cluster: "🥵", Name: "hot face", Keywords: []string{"hot", "heat", "sweat"}},
	{Cluster: "🥶", Name: "cold face", Keywords: []string{"cold", "freezing"}},
	{Cluster: "😵", Name: "face with crossed-out eyes", Keywords: []string{"dizzy", "dead"}},
	{Cluster: "🤯", Name: "exploding head", Keywords: []string{"mind blown", "shock", "wow"}},
	{Cluster: "🤠", Name: "cowboy hat face", Keywords: []string{"cowboy", "yeehaw"}},
	{Cluster: "🥺", Name: "pleading face", Keywords: []string{"please", "beg", "puppy eyes"}},
	{Cluster: "😢", Name: "crying face", Keywords: []string{"sad", "tear"}},
	{Cluster: "😭", Name: "loudly crying face", Keywords: []string{"sob", "sad", "cry"}},
	{Cluster: "😤", Name: "face with steam from nose", Keywords: []string{"angry", "determined"}},
	{Cluster: "😠", Name: "angry face", Keywords: []string{"mad", "angry"}},
	{Cluster: "😡", Name: "enraged face", Keywords: []string{"rage", "angry"}},
	{Cluster: "🤬", Name: "face with symbols on mouth", Keywords: []string{"swearing", "censored"}},
	{Cluster: "😱", Name: "face screaming in fear", Keywords: []string{"scream", "shock"}},
	{Cluster: "😨", Name: "fearful face", Keywords: []string{"scared", "fear"}},
	{Cluster: "😰", Name: "anxious face with sweat", Keywords: []string{"nervous", "worried"}},
	{Cluster: "😳", Name: "flushed face", Keywords: []string{"blush", "surprised"}},
	{Cluster: "🥴", Name: "woozy face", Keywords: []string{"woozy", "confused"}},
	{Cluster: "😬", Name: "grimacing face", Keywords: []string{"awkward", "yikes"}},
	{Cluster: "🙄", Name: "face with rolling eyes", Keywords: []string{"eyeroll", "annoyed"}},
	{Cluster: "🤔", Name: "thinking face", Keywords: []string{"think", "hmm", "consider"}},
	{Cluster: "🤫", Name: "shushing face", Keywords: []string{"quiet", "shh", "spoiler"}},
	{Cluster: "🤐", Name: "zipper-mouth face", Keywords: []string{"quiet", "secret"}},
	{Cluster: "😶", Name: "face without mouth", Keywords: []string{"speechless", "silent"}},
	{Cluster: "😐", Name: "neutral face", Keywords: []string{"deadpan", "meh"}},
	{Cluster: "😑", Name: "expressionless face", Keywords: []string{"blank", "meh"}},
	{Cluster: "🤡", Name: "clown face", Keywords: []string{"clown", "joke"}},
	{Cluster: "💀", Name: "skull", Keywords: []string{"dead", "dying", "lol"}},
	{Cluster: "👻", Name: "ghost", Keywords: []string{"boo", "spooky"}},
	{Cluster: "👽", Name: "alien", Keywords: []string{"ufo", "space"}},
	{Cluster: "🤖", Name: "robot", Keywords: []string{"bot", "automation"}},
	{Cluster: "😺", Name: "grinning cat", Keywords: []string{"cat", "smile"}},
	{Cluster: "😹", Name: "cat with tears of joy", Keywords: []string{"cat", "laugh"}},

	// Gestures. Skin-tone modifiers are valid clusters; the picker ships the
	// neutral form and the composer keeps whatever the user pastes.
	{Cluster: "👋", Name: "waving hand", Keywords: []string{"hello", "hi", "bye", "wave"}},
	{Cluster: "👍", Name: "thumbs up", Keywords: []string{"yes", "like", "approve", "up"}},
	{Cluster: "👎", Name: "thumbs down", Keywords: []string{"no", "dislike", "down"}},
	{Cluster: "👏", Name: "clapping hands", Keywords: []string{"applause", "clap", "bravo"}},
	{Cluster: "🙌", Name: "raising hands", Keywords: []string{"celebrate", "praise", "hype"}},
	{Cluster: "🙏", Name: "folded hands", Keywords: []string{"please", "thanks", "pray"}},
	{Cluster: "🤝", Name: "handshake", Keywords: []string{"deal", "agree"}},
	{Cluster: "✌️", Name: "victory hand", Keywords: []string{"peace", "two"}},
	{Cluster: "🤞", Name: "crossed fingers", Keywords: []string{"luck", "hope"}},
	{Cluster: "🤙", Name: "call me hand", Keywords: []string{"shaka", "hang loose"}},
	{Cluster: "🤟", Name: "love-you gesture", Keywords: []string{"love", "ily"}},
	{Cluster: "🤘", Name: "sign of the horns", Keywords: []string{"rock", "metal"}},
	{Cluster: "👌", Name: "OK hand", Keywords: []string{"ok", "perfect"}},
	{Cluster: "🫡", Name: "saluting face", Keywords: []string{"salute", "respect", "o7"}},
	{Cluster: "✊", Name: "raised fist", Keywords: []string{"fist", "solidarity"}},
	{Cluster: "👊", Name: "oncoming fist", Keywords: []string{"bump", "punch"}},
	{Cluster: "☝️", Name: "index pointing up", Keywords: []string{"point", "one", "actually"}},
	{Cluster: "👀", Name: "eyes", Keywords: []string{"look", "watching", "sus"}},
	{Cluster: "🧠", Name: "brain", Keywords: []string{"smart", "big brain"}},
	{Cluster: "💪", Name: "flexed biceps", Keywords: []string{"strong", "muscle", "gains"}},

	// Hearts and love. Super Chats attract these.
	{Cluster: "❤️", Name: "red heart", Keywords: []string{"love", "heart"}},
	{Cluster: "🧡", Name: "orange heart", Keywords: []string{"love", "heart"}},
	{Cluster: "💛", Name: "yellow heart", Keywords: []string{"love", "heart"}},
	{Cluster: "💚", Name: "green heart", Keywords: []string{"love", "heart"}},
	{Cluster: "💙", Name: "blue heart", Keywords: []string{"love", "heart"}},
	{Cluster: "💜", Name: "purple heart", Keywords: []string{"love", "heart"}},
	{Cluster: "🖤", Name: "black heart", Keywords: []string{"love", "heart"}},
	{Cluster: "🤍", Name: "white heart", Keywords: []string{"love", "heart"}},
	{Cluster: "💖", Name: "sparkling heart", Keywords: []string{"love", "sparkle"}},
	{Cluster: "💗", Name: "growing heart", Keywords: []string{"love", "heart"}},
	{Cluster: "💕", Name: "two hearts", Keywords: []string{"love", "hearts"}},
	{Cluster: "💔", Name: "broken heart", Keywords: []string{"sad", "heartbreak"}},

	// Stream furniture: the things a live chat points at.
	{Cluster: "🔴", Name: "red circle", Keywords: []string{"live", "record", "on air"}},
	{Cluster: "🟢", Name: "green circle", Keywords: []string{"online", "ok", "go"}},
	{Cluster: "🟡", Name: "yellow circle", Keywords: []string{"warning", "waiting"}},
	{Cluster: "▶️", Name: "play button", Keywords: []string{"play", "start", "video"}},
	{Cluster: "⏸️", Name: "pause button", Keywords: []string{"pause", "brb"}},
	{Cluster: "⏹️", Name: "stop button", Keywords: []string{"stop", "end"}},
	{Cluster: "⏺️", Name: "record button", Keywords: []string{"record", "rec"}},
	{Cluster: "⏩", Name: "fast-forward button", Keywords: []string{"skip", "forward"}},
	{Cluster: "📺", Name: "television", Keywords: []string{"stream", "tv", "watch"}},
	{Cluster: "📹", Name: "video camera", Keywords: []string{"camera", "record", "stream"}},
	{Cluster: "🎥", Name: "movie camera", Keywords: []string{"film", "camera"}},
	{Cluster: "🎬", Name: "clapper board", Keywords: []string{"action", "film", "take"}},
	{Cluster: "🎙️", Name: "studio microphone", Keywords: []string{"mic", "podcast", "audio"}},
	{Cluster: "🎤", Name: "microphone", Keywords: []string{"mic", "sing", "karaoke"}},
	{Cluster: "🎧", Name: "headphone", Keywords: []string{"audio", "listen", "music"}},
	{Cluster: "🔊", Name: "speaker high volume", Keywords: []string{"loud", "audio", "volume"}},
	{Cluster: "🔇", Name: "muted speaker", Keywords: []string{"mute", "silence"}},
	{Cluster: "💬", Name: "speech balloon", Keywords: []string{"chat", "message", "talk"}},
	{Cluster: "📢", Name: "loudspeaker", Keywords: []string{"announce", "shout"}},
	{Cluster: "🔔", Name: "bell", Keywords: []string{"notify", "subscribe", "alert"}},
	{Cluster: "🔕", Name: "bell with slash", Keywords: []string{"mute", "silence", "notify"}},
	{Cluster: "⚠️", Name: "warning", Keywords: []string{"caution", "warning"}},
	{Cluster: "⛔", Name: "no entry", Keywords: []string{"stop", "blocked", "banned"}},
	{Cluster: "🚫", Name: "prohibited", Keywords: []string{"no", "ban", "denied"}},
	{Cluster: "🔨", Name: "hammer", Keywords: []string{"ban", "mod", "hammer"}},
	{Cluster: "🛡️", Name: "shield", Keywords: []string{"mod", "protect", "guard"}},
	{Cluster: "⚔️", Name: "crossed swords", Keywords: []string{"mod", "fight", "battle"}},
	{Cluster: "👑", Name: "crown", Keywords: []string{"owner", "king", "queen", "best"}},
	{Cluster: "⭐", Name: "star", Keywords: []string{"member", "favorite", "star"}},
	{Cluster: "🌟", Name: "glowing star", Keywords: []string{"shine", "star", "special"}},
	{Cluster: "✨", Name: "sparkles", Keywords: []string{"shine", "new", "magic"}},
	{Cluster: "💎", Name: "gem stone", Keywords: []string{"diamond", "jewel", "gift"}},
	{Cluster: "🎁", Name: "wrapped gift", Keywords: []string{"gift", "present", "membership"}},
	{Cluster: "🎉", Name: "party popper", Keywords: []string{"celebrate", "party", "congrats"}},
	{Cluster: "🎊", Name: "confetti ball", Keywords: []string{"celebrate", "party"}},
	{Cluster: "🏆", Name: "trophy", Keywords: []string{"win", "champion", "award"}},
	{Cluster: "🥇", Name: "1st place medal", Keywords: []string{"gold", "first", "win"}},
	{Cluster: "💰", Name: "money bag", Keywords: []string{"money", "super chat", "donate"}},
	{Cluster: "💵", Name: "dollar banknote", Keywords: []string{"money", "cash", "donate"}},
	{Cluster: "🪙", Name: "coin", Keywords: []string{"money", "coin", "tip"}},

	// Everyday objects and tech.
	{Cluster: "💻", Name: "laptop", Keywords: []string{"computer", "code", "work"}},
	{Cluster: "🖥️", Name: "desktop computer", Keywords: []string{"pc", "monitor"}},
	{Cluster: "⌨️", Name: "keyboard", Keywords: []string{"type", "keys"}},
	{Cluster: "🖱️", Name: "computer mouse", Keywords: []string{"mouse", "click"}},
	{Cluster: "📱", Name: "mobile phone", Keywords: []string{"phone", "mobile"}},
	{Cluster: "🔋", Name: "battery", Keywords: []string{"power", "charge"}},
	{Cluster: "🔌", Name: "electric plug", Keywords: []string{"power", "plug"}},
	{Cluster: "💡", Name: "light bulb", Keywords: []string{"idea", "tip"}},
	{Cluster: "🔍", Name: "magnifying glass", Keywords: []string{"search", "find", "zoom"}},
	{Cluster: "🔒", Name: "locked", Keywords: []string{"lock", "private", "secure"}},
	{Cluster: "🔓", Name: "unlocked", Keywords: []string{"unlock", "open"}},
	{Cluster: "🔑", Name: "key", Keywords: []string{"key", "access", "auth"}},
	{Cluster: "📝", Name: "memo", Keywords: []string{"note", "write", "edit"}},
	{Cluster: "📌", Name: "pushpin", Keywords: []string{"pin", "pinned"}},
	{Cluster: "📎", Name: "paperclip", Keywords: []string{"attach", "link"}},
	{Cluster: "🔗", Name: "link", Keywords: []string{"url", "link", "chain"}},
	{Cluster: "📊", Name: "bar chart", Keywords: []string{"stats", "chart", "quota"}},
	{Cluster: "📈", Name: "chart increasing", Keywords: []string{"up", "growth", "stats"}},
	{Cluster: "📉", Name: "chart decreasing", Keywords: []string{"down", "drop", "stats"}},
	{Cluster: "🐛", Name: "bug", Keywords: []string{"bug", "issue", "broken"}},
	{Cluster: "⚙️", Name: "gear", Keywords: []string{"settings", "config"}},
	{Cluster: "🔧", Name: "wrench", Keywords: []string{"fix", "tool", "repair"}},
	{Cluster: "🚀", Name: "rocket", Keywords: []string{"launch", "ship", "fast"}},
	{Cluster: "🔥", Name: "fire", Keywords: []string{"hot", "lit", "fire"}},
	{Cluster: "⚡", Name: "high voltage", Keywords: []string{"fast", "power", "energy"}},
	{Cluster: "💥", Name: "collision", Keywords: []string{"boom", "explosion"}},
	{Cluster: "🌈", Name: "rainbow", Keywords: []string{"pride", "color"}},
	{Cluster: "☀️", Name: "sun", Keywords: []string{"sunny", "day", "light"}},
	{Cluster: "🌙", Name: "crescent moon", Keywords: []string{"night", "late", "sleep"}},
	{Cluster: "⏰", Name: "alarm clock", Keywords: []string{"time", "alarm", "late"}},
	{Cluster: "⌛", Name: "hourglass done", Keywords: []string{"wait", "time", "loading"}},

	// Food and drink, the second most-sent category in a long stream.
	{Cluster: "☕", Name: "hot beverage", Keywords: []string{"coffee", "tea", "brb"}},
	{Cluster: "🍵", Name: "teacup", Keywords: []string{"tea", "green tea"}},
	{Cluster: "🍺", Name: "beer mug", Keywords: []string{"beer", "drink", "cheers"}},
	{Cluster: "🥤", Name: "cup with straw", Keywords: []string{"soda", "drink"}},
	{Cluster: "🍕", Name: "pizza", Keywords: []string{"food", "pizza"}},
	{Cluster: "🍔", Name: "hamburger", Keywords: []string{"food", "burger"}},
	{Cluster: "🍿", Name: "popcorn", Keywords: []string{"watching", "drama", "movie"}},
	{Cluster: "🍰", Name: "shortcake", Keywords: []string{"cake", "dessert"}},
	{Cluster: "🎂", Name: "birthday cake", Keywords: []string{"birthday", "celebrate"}},
	{Cluster: "🍩", Name: "doughnut", Keywords: []string{"donut", "snack"}},
	{Cluster: "🍪", Name: "cookie", Keywords: []string{"snack", "cookie"}},

	// Animals and plants.
	{Cluster: "🐱", Name: "cat face", Keywords: []string{"cat", "kitty"}},
	{Cluster: "🐶", Name: "dog face", Keywords: []string{"dog", "puppy"}},
	{Cluster: "🦊", Name: "fox", Keywords: []string{"fox"}},
	{Cluster: "🐼", Name: "panda", Keywords: []string{"panda", "bear"}},
	{Cluster: "🐸", Name: "frog", Keywords: []string{"frog"}},
	{Cluster: "🐢", Name: "turtle", Keywords: []string{"slow", "turtle", "lag"}},
	{Cluster: "🦀", Name: "crab", Keywords: []string{"crab", "rust"}},
	{Cluster: "🐍", Name: "snake", Keywords: []string{"snake", "python"}},
	{Cluster: "🌸", Name: "cherry blossom", Keywords: []string{"flower", "spring"}},
	{Cluster: "🌱", Name: "seedling", Keywords: []string{"plant", "growth", "new"}},

	// Symbols and marks.
	{Cluster: "✅", Name: "check mark button", Keywords: []string{"done", "yes", "ok"}},
	{Cluster: "❌", Name: "cross mark", Keywords: []string{"no", "wrong", "error"}},
	{Cluster: "❗", Name: "exclamation mark", Keywords: []string{"important", "alert"}},
	{Cluster: "❓", Name: "question mark", Keywords: []string{"question", "help"}},
	{Cluster: "💯", Name: "hundred points", Keywords: []string{"100", "perfect", "agree"}},
	{Cluster: "🆗", Name: "OK button", Keywords: []string{"ok", "fine"}},
	{Cluster: "🆕", Name: "NEW button", Keywords: []string{"new"}},
	{Cluster: "🔞", Name: "no one under eighteen", Keywords: []string{"18", "adult"}},
	{Cluster: "➡️", Name: "right arrow", Keywords: []string{"next", "right"}},
	{Cluster: "⬅️", Name: "left arrow", Keywords: []string{"back", "left"}},
	{Cluster: "⬆️", Name: "up arrow", Keywords: []string{"up", "above"}},
	{Cluster: "⬇️", Name: "down arrow", Keywords: []string{"down", "below"}},
	{Cluster: "🔁", Name: "repeat button", Keywords: []string{"loop", "repeat", "again"}},
	{Cluster: "🎯", Name: "bullseye", Keywords: []string{"target", "exact", "goal"}},
	{Cluster: "🎮", Name: "video game", Keywords: []string{"game", "gaming", "controller"}},
	{Cluster: "🎲", Name: "game die", Keywords: []string{"dice", "random", "luck"}},
	{Cluster: "🧩", Name: "puzzle piece", Keywords: []string{"puzzle", "piece", "fit"}},
	{Cluster: "🏁", Name: "checkered flag", Keywords: []string{"finish", "end", "race"}},
	{Cluster: "🌍", Name: "globe showing europe-africa", Keywords: []string{"world", "earth", "global"}},
}
